name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 # 使用 setup-python action
        with:
          python-version: '3.11.9' # 指定 Python 版本，可依需求調整

      - name: Install dependencies
        run: | # 運行多行指令
          python -m pip install --upgrade pip # 升級 pip
          pip install -r requirements.txt # 安裝專案依賴（假設有 requirements.txt）

      - name: Run tests
        run: |
          # 運行 Python 測試。這裡以 pytest 為例，請根據您的測試框架調整
          pip install pytest # 如果測試依賴 pytest，需要先安裝
          pytest # 執行 pytest
# ... (在 Run tests 之前或之後)
- name: Run Linter
  run: |
    pip install flake8 # 安裝 flake8
    flake8 . # 執行 flake8 檢查
